//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwaijaComposite.Modules.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColumnTypeKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColumnTypeKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwaijaComposite.Modules.Common.Resources.ColumnTypeKeys", typeof(ColumnTypeKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterConversation.
        /// </summary>
        public static string TwitterConversationKey {
            get {
                return ResourceManager.GetString("TwitterConversationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterDirectMessages.
        /// </summary>
        public static string TwitterDirectMessagesKey {
            get {
                return ResourceManager.GetString("TwitterDirectMessagesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterFavourites.
        /// </summary>
        public static string TwitterFavouritesKey {
            get {
                return ResourceManager.GetString("TwitterFavouritesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterFollowers.
        /// </summary>
        public static string TwitterFollowersKey {
            get {
                return ResourceManager.GetString("TwitterFollowersKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterFriends.
        /// </summary>
        public static string TwitterFriendsKey {
            get {
                return ResourceManager.GetString("TwitterFriendsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterHometimeline.
        /// </summary>
        public static string TwitterHometimelineKey {
            get {
                return ResourceManager.GetString("TwitterHometimelineKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterMentions.
        /// </summary>
        public static string TwitterMentionsKey {
            get {
                return ResourceManager.GetString("TwitterMentionsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterProfile.
        /// </summary>
        public static string TwitterProfileKey {
            get {
                return ResourceManager.GetString("TwitterProfileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterRefreshableTimeline.
        /// </summary>
        public static string TwitterRefreshableTimelineKey {
            get {
                return ResourceManager.GetString("TwitterRefreshableTimelineKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterTrends.
        /// </summary>
        public static string TwitterTrendsKey {
            get {
                return ResourceManager.GetString("TwitterTrendsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterTweetSearch.
        /// </summary>
        public static string TwitterTweetSearchKey {
            get {
                return ResourceManager.GetString("TwitterTweetSearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterUserSearch.
        /// </summary>
        public static string TwitterUserSearchKey {
            get {
                return ResourceManager.GetString("TwitterUserSearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwitterUserTimeline.
        /// </summary>
        public static string TwitterUserTimelineKey {
            get {
                return ResourceManager.GetString("TwitterUserTimelineKey", resourceCulture);
            }
        }
    }
}
