//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwaijaComposite.Modules.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateColumnEventParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateColumnEventParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwaijaComposite.Modules.Common.Resources.CreateColumnEventParameters", typeof(CreateColumnEventParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeographicalLocation.
        /// </summary>
        public static string GeographicalLocationKey {
            get {
                return ResourceManager.GetString("GeographicalLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoString.
        /// </summary>
        public static string GeoStringKey {
            get {
                return ResourceManager.GetString("GeoStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeKey {
            get {
                return ResourceManager.GetString("LatitudeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeKey {
            get {
                return ResourceManager.GetString("LongitudeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximumDate.
        /// </summary>
        public static string MaximumDateKey {
            get {
                return ResourceManager.GetString("MaximumDateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelFactory.
        /// </summary>
        public static string ModelFactoryKey {
            get {
                return ResourceManager.GetString("ModelFactoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SinceDate.
        /// </summary>
        public static string SinceDateKey {
            get {
                return ResourceManager.GetString("SinceDateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetScreenName.
        /// </summary>
        public static string TargetScreenNameKey {
            get {
                return ResourceManager.GetString("TargetScreenNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetUserId.
        /// </summary>
        public static string TargetUserIdKey {
            get {
                return ResourceManager.GetString("TargetUserIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextKey {
            get {
                return ResourceManager.GetString("TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TweetId.
        /// </summary>
        public static string TweetIdKey {
            get {
                return ResourceManager.GetString("TweetIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet.
        /// </summary>
        public static string TweetKey {
            get {
                return ResourceManager.GetString("TweetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOEID.
        /// </summary>
        public static string WOEIDKey {
            get {
                return ResourceManager.GetString("WOEIDKey", resourceCulture);
            }
        }
    }
}
